---
format: pdf
editor: source
---

# Plan de cours : Science des données III : exploration et prédiction

```{r, echo=FALSE}
library(glue)
year <- "2025-2026"
year1 <- "2025"
```

## année académique `r glue::glue(year)`

## Enseignants

-   Enseignant : Philippe Grosjean
-   Assistant : Guyliann Engels

## Présentation du cours

La science des données s'intéresse à l'analyse des données sous toutes ses formes. Cette discipline requiert des compétences en informatiques, en mathématiques et dans le domaine d'expertise. La Science fait actuellement face à de nombreux changements suite à l'introduction de l'Open Science, de l'Open Data, de l'augmentation exponentielle des données, ... Les biologistes doivent être capables d'évoluer dans ce contexte grâce à une bonne connaissance de la science des données biologiques.

Ce troisième cours s'inscrit dans une formation continue sur trois années successives. À la fin de ce cours, les étudiants seront capables d'employer des méthodes de classification supervisées, de traiter des séries spatio-temporelles, de réaliser des cartes géographiques avec des données spatialisées et de présenter clairement leurs résultats de manière reproductible avec des outils informatiques et statistiques professionnels.

La fiche ECTS reprend toutes les informations essentielles :

<`r glue("http://applications.umons.ac.be/web/fr/pde/{year}/ue/US-M1-BIOECO-004-M.htm")`>

## Organisation

Le cours de [Science des données III : exploration et prédiction](%60r%20glue(%22http://applications.umons.ac.be/web/fr/pde/%7Byear%7D/ue/US-M1-BIOECO-004-M.htm%22)%60) est une unité d'enseignement (UE) de trois crédits. Ce cours est composé de cinq modules. Chaque module représente une charge moyenne de travail de 15 à 18h dont 6h en présentiel et le reste en travail personnel à domicile. Vous pouvez retrouver à l'horaire les plages en présentiel et le travail à distance est à réaliser entre ces sessions. Toutes les heures en présentiel sont assimilées à des heures de travaux pratiques encadrées avec **présence obligatoire**. Chaque absence doit être justifiée.

## Modules

Science des données III : exploration et prédiction

-   Classification supervisée I, LDA, principe général, matrice de confusion, métriques
-   Classification supervisée II, validation croisée, AUC, k-nn, lvq, rpart, random forest
-   Classification supervisée III, svm, réseaux de neurones, initiation au deep learning
-   Séries temporelles I, caractéristiques, manipulation, acf, analyse spectrale
-   Séries temporelles II, décomposition et régularisation

## Méthode pédagogique

Ce cours est donné en classe **inversée** avec l'ensemble du matériel pédagogique disponible via le lien <http://bds.sciviews.org/>. Les étudiants seront actifs à chaque étape de l'apprentissage. Chaque module de cours comprend des exercices classés en quatre niveaux de difficulté croissante.

-   niveau 1 : découverte des notions avec des exercices rapides et ciblés intégrés au sein du cours en ligne
-   niveau 2 : application des notions dans des exercices sous la forme de tutoriel cadré
-   niveau 3 : transfert de ces notions dans des projets individuels guidés et réalisés sur des données biologiques
-   niveau 4 : réalisation d'analyses libres dans des projets de groupe et sur des données biologiques nouvelles

De plus, des challenges pratiques et des interrogations vont être réalisés durant les séances en présentiel. Néanmoins, la plus grande partie de votre temps sera consacrée à l'analyse de données biologiques au sein des exercices de niveau 3 et 4.

**L'apprentissage nécessite de poser régulièrement des questions.** Le canal privilégié pour ces échanges est constitué des "issues" dans GitHub, accessibles depuis le site du cours. Vous pouvez également nous contacter par mail à l'adresse [sdd\@sciviews.org](mailto:sdd@sciviews.org){.email}, mais uniquement pour les questions à caractère privé par rapport aux autres étudiants, pas pour les questions sur la matière elle-même.

## Évaluation

L'activité dans les différents exercices est enregistrée pour chaque étudiant et est utilisée pour une évaluation continue. **Il n'y a pas d'examen en session, ni d'examen de seconde session pour cette matière.** Il faut avoir réalisé au minimum 80% des exercices de chaque module pour qu'il soit pris en compte dans l'évaluation.

La note de l'UE est obtenue par addition des composantes suivantes :

-   6% pour les exercices à préparer en distanciel :
    -   2%, exercices N1 (H5P + shiny)
    -   4%, exercices N2 (learnr)
-   34% pour les projets, soit :
    -   6%, projets individuels cadrés N3
    -   28%, projets de groupe N4
-   60% pour des interrogations (ou challenges) relatives à un module (12%) ou deux modules (24%). En cas d'une absence justifiée, l'évaluation pourra être réalisée dans les sept jours suivants. Toute absence injustifiée est sanctionnée par un zéro pour l'évaluation correspondante.

Pour les raisons énumérées suivantes, il est envisageable d’obtenir entre un demi et un point bonus sur la note finale sur 20 pour :

-   une participation active et remarquable dans la résolution d'"issues"
-   une aide significative apportée à vos collègues sous la forme d'explications de la matière en séance
-   une réflexion approfondie sur la matière (hors aspects purement techniques) accompagnée d'échanges avec les encadrants
-   une progression particulièrement importante dans l'apprentissage

## Entraide versus plagiat

L'entraide entre les étudiants est encouragée, mais il faut citer ses sources. Le plagiat est par contre totalement **interdit** et sévèrement puni à l'UMONS. Les étudiants devront bien comprendre la différence entre les deux dans le cadre du cours.

## Usage de l'intelligence artificielle générative

Conformément à la Charte d'utilisation des systèmes d'intelligence artificielle générative pour les travaux universitaires à l'UMONS, l'usage de l'intelligence artificielle générative est autorisé. Il est essentiel d'adopter une utilisation responsable, critique et transparente de l'IA.

Il est **obligatoire** de mentionner dans la section *Matériel et méthodes* de tous les projets réalisés, l'utilisation de l'IA, du modèle consulté, ainsi que le contexte dans lequel celui-ci a été utilisée.

L'utilisation de l'IA en tant qu'outil d'assistance linguistique, de recherche d'informations ou encore d'assistance à la programmation est autorisée. Le code proposé devra toutefois respecter le "dialecte" SciViews::R qui diffère significativement du R de base. **Tout code issu d'une IA en R de base ou en tidyverse devra être converti manuellement en SciViews::R sous peine de pénalités.**

Restez cependant critique vis-à-vis de l'information proposée par l'IA.

## Équipement requis

-   un ordinateur (en option)

Les heures en présentiel sont données dans des salles informatiques équipées d'ordinateurs. Il est conseillé d'utiliser son ordinateur personnel pour les étudiants qui en disposent. Cela simplifie le travail en distanciel.

-   des écouteurs

Des vidéos sont présentes dans le cours en ligne et il faut pouvoir les écouter avec le son sans déranger ses voisins.

-   un câble ethernet (en option)

Il s'agit d'un câble RJ-45 non croisé de catégorie 5E ou plus d'au moins 1m, avec adaptateur si nécessaire pour le connecter sur votre ordinateur (par exemple, USB -\> RJ-45). La connexion filaire permet un accès à Internet plus stable et plus rapide que le Wifi.

L'UMONS met également des salles informatiques à disposition des étudiants qui ne disposent pas de leur propre PC. Le travail dans les salles informatiques doit se faire dans le respect de la **charte informatique de l'UMONS**, voir <https://go.sciviews.org/charte_info>.

## Protection de la vie privée

La collecte des données personnelles des étudiants dans le cadre de ce cours se fait en respect du RGPD, voir <https://wp.sciviews.org/politique-de-confidentialite/>.

## Ressources

-   Site web du cours <https://wp.sciviews.org/>
-   horaire des cours \<`r glue("https://hplanning{year1}.umons.ac.be/invite")`\>
-   Ressource Moodle : <https://moodle.umons.ac.be/course/view.php?id=1464>
-   Fiche ECTS du cours : \<`r glue("http://applications.umons.ac.be/web/fr/pde/{year}/ue/US-M1-BIOECO-004-M.htm")`\>
-   Définition du plagiat et les sanction à l'UMONS : <https://alumniumonsac.sharepoint.com/sites/SAP_Etudiants/SitePages/Plagiat(1).aspx>
-   Je ne plagie pas ... enfin, je pense : <https://alumniumonsac.sharepoint.com/sites/SAP_Etudiants/SitePages/Plagiat.aspx>
-   Charte informatique de l'UMONS : <https://go.sciviews.org/charte_info>
-   Charte d'utilisation des systèmes d'intelligence artificielle générative dans les travaux universitaires à l'UMONS : <https://go.sciviews.org/charte_ia_umons>
